name: Build and deploy Python app to Azure Web App - flask2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3  # Use the latest stable version of checkout

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5  # Use the latest stable version of setup-python
        with:
          python-version: '3.8'

      # Step 3: Create and activate a virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # Step 5: Upload artifact for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3  # Use the latest version for uploading artifacts
        with:
          name: python-app
          path: |
            .
            venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      # Step 1: Download artifact from build
      - name: Download build artifact
        uses: actions/download-artifact@v3  # Use the latest version for downloading artifacts
        with:
          name: python-app

      # Step 2: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3  # Use the latest version of azure/webapps-deploy
        id: deploy-to-azure-web-app
        with:
          app-name: <YOUR_APP_NAME>  # Replace with your Azure app name
          slot-name: 'Production'
          publish-profile: ${{ secrets.MY_SECRET }}  # Use correct secret name
          package: .
